

import { BackendForm } from "backend-manager/backend-form.slint";
import { VerticalBox } from "std-widgets.slint";
import {BackendManagerAdapter,BackendPages} from "backend-manager-adapter.slint";
import { BackendList } from "backend-manager/backend-list.slint";

export component BackendManager {
    VerticalLayout {
        if BackendManagerAdapter.page == BackendPages.List: BackendList {}
        if BackendManagerAdapter.page == BackendPages.Add: BackendForm {}
    }
}