import {Error} from "../lib/error.slint";

export enum BackendType {
    Local
}
export struct Backend {
    id: string, // format: uuid 
    name: string,
    type: BackendType,
}

export struct BackendDraft {
    name: string,
    type: BackendType,
}

export global BackendRepository {
    property <int> name;
    pure callback add(BackendDraft)->{err: Error, result: string /** Backend.id */};
    pure callback getAll()-> [Backend];
    pure callback get(string /** Backend.id */)->{err: Error, result: Backend};
}