
import { LineEdit , ComboBox, HorizontalBox, GroupBox, VerticalBox, Button, GridBox} from "std-widgets.slint";
import {BackendRepository,BackendDraft,BackendType} from "../../../singletons/backend_repository.slint";
import {LocalBackendRepository} from "../../../singletons/local_backend_repository.slint";
import {PathLib} from "../../../singletons/path_lib.slint";
import {Error} from "../../../lib/error.slint";

export component BackendForm {
    property <string> name <=> nameElm.text;
    property <string> type <=> typeElm.current-value; 
    property <string> path <=> pathElm.text; 
    property <string> errorText;

    property <{err:Error, result: string}> backend-add-result;
    property <Error> local-backend-edit-result;
    
    function clearHandleSubmitVariables() {
        backend-add-result = {err: {did_occured:false, message:""}, result:""};
        local-backend-edit-result = {did_occured:false, message:""};
    }

    init => {
        clearHandleSubmitVariables();
    }

    function handleSubmit(){
        if(type=="Local"){
            backend-add-result = BackendRepository.add({
                name: name,
                type: BackendType.Local
            });
            if(backend-add-result.err.did-occured){
                errorText = "backend repository error:" + backend-add-result.err.message;
            }
            local-backend-edit-result = LocalBackendRepository.edit({backend_id: backend-add-result.result, path: path});
            if(local-backend-edit-result.did-occured){
                errorText = "local backend repository error:" + local-backend-edit-result.message;
            }
        }

        clearHandleSubmitVariables();
    }
    VerticalBox {
        HorizontalBox {
            alignment: start;
            GroupBox {
                title: "Name";
                nameElm := TextInput {
                    single-line: false;
                    accepted() => {debug("Enter");}
                }
            }
            GroupBox {
                title: "Type";
                typeElm := ComboBox {
                    model: ["Local"];
                }
            }
        }
        HorizontalBox {
            GroupBox {
                title: "Path";
                pathElm := LineEdit {
                    text: PathLib.home-dir;
                }
            }
        }
        if errorText != "": HorizontalBox{
            Text{text: errorText;}
        }
        HorizontalBox {
            alignment: start;
            Button {
                text: "Save";
                clicked=>{handleSubmit()}
            }
        }
    }
}