import { Taskbar } from "taskbar/taskbar.slint";
import { BackendManager } from "pages/home/backend-manager.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import {AddLocalBackendUsecase,AddLocalBackendArgs} from "singletons/add_local_backend_usecase.slint";
import {PathLib} from "singletons/path_lib.slint";
import {Error} from "lib/error.slint";
import {Backend} from "models/backend.slint";
import {LocalBackend} from "models/local_backend.slint";

export {AddLocalBackendUsecase,AddLocalBackendArgs,Backend, LocalBackend,PathLib,Error}

export component AppWindow inherits Window {
    VerticalLayout {
        alignment: start;
        Taskbar {}
        BackendManager {}
    }
}
