import { Taskbar } from "taskbar/taskbar.slint";
import { BackendManager } from "pages/home/backend-manager.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import {BackendRepository,BackendDraft} from "singletons/backend_repository.slint";
import {LocalBackendRepository} from "singletons/local_backend_repository.slint";
import {PathLib} from "singletons/path_lib.slint";
import {Error} from "lib/error.slint";

export {BackendRepository,BackendDraft, LocalBackendRepository,PathLib,Error}

export component AppWindow inherits Window {
    VerticalLayout {
        alignment: start;
        Taskbar {}
        BackendManager {}
    }
}
